title: <p align="center"> Mohammed Elbashier </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/melbashier/">LinkedIn</a> |
  <a href="https://github.com/elbashier">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing a career in Machine Learning.
  <br><br>
  I am currently a Data Scientist at DS-I Africa.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
